version: '3.7'
services:
  ai-battle-db:
    image: 'mysql'
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${MAINDB_NAME}
    ports:
      - 3306:3306
    volumes:
      - cs492i:/var/lib/mysql
    container_name: ai-battle-db
    command: --default-authentication-plugin=mysql_native_password

  cs492i-api-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    volumes:
      - ./src:/home/node/app/src
    container_name: cs492i-api-server
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - ai-battle-db
    entrypoint:
      - /home/node/app/entrypoint.sh

volumes:
  cs492i:
